-- Azure SQL member/claims source schema. Synthetic data only.
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name='payer') EXEC('CREATE SCHEMA payer');
CREATE TABLE payer.members (member_id BIGINT NOT NULL PRIMARY KEY, enterprise_person_id UNIQUEIDENTIFIER NOT NULL, first_name NVARCHAR(80) NOT NULL, last_name NVARCHAR(80) NOT NULL, date_of_birth DATE NOT NULL, sex CHAR(1) NOT NULL CHECK(sex IN ('F','M','X','U')), member_number VARCHAR(40) NOT NULL UNIQUE, email VARCHAR(254), phone VARCHAR(30), modified_at DATETIME2(3) NOT NULL, is_deleted BIT NOT NULL DEFAULT 0, source_schema_version VARCHAR(20) NOT NULL DEFAULT 'v1');
CREATE TABLE payer.plans (plan_id INT NOT NULL PRIMARY KEY, plan_code VARCHAR(30) NOT NULL UNIQUE, plan_name NVARCHAR(120) NOT NULL, plan_type VARCHAR(30) NOT NULL, region_code VARCHAR(10) NOT NULL, modified_at DATETIME2(3) NOT NULL, is_deleted BIT NOT NULL DEFAULT 0);
CREATE TABLE payer.member_enrollment (enrollment_id BIGINT NOT NULL PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES payer.members(member_id), plan_id INT NOT NULL REFERENCES payer.plans(plan_id), coverage_start_date DATE NOT NULL, coverage_end_date DATE NULL, status VARCHAR(20) NOT NULL, modified_at DATETIME2(3) NOT NULL, is_deleted BIT NOT NULL DEFAULT 0, CONSTRAINT ck_enrollment_dates CHECK(coverage_end_date IS NULL OR coverage_end_date>=coverage_start_date));
CREATE TABLE payer.claims (claim_id BIGINT NOT NULL PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES payer.members(member_id), provider_id BIGINT NOT NULL, facility_id BIGINT NOT NULL, claim_number VARCHAR(40) NOT NULL UNIQUE, service_start_date DATE NOT NULL, service_end_date DATE NOT NULL, received_date DATE NOT NULL, status VARCHAR(20) NOT NULL, billed_amount DECIMAL(14,2) NOT NULL CHECK(billed_amount>=0), allowed_amount DECIMAL(14,2) NOT NULL CHECK(allowed_amount>=0 AND allowed_amount<=billed_amount), paid_amount DECIMAL(14,2) NOT NULL CHECK(paid_amount>=0 AND paid_amount<=allowed_amount), modified_at DATETIME2(3) NOT NULL, is_deleted BIT NOT NULL DEFAULT 0, source_schema_version VARCHAR(20) NOT NULL DEFAULT 'v1', CONSTRAINT ck_claim_dates CHECK(service_end_date>=service_start_date));
CREATE TABLE payer.claim_lines (claim_line_id BIGINT NOT NULL PRIMARY KEY, claim_id BIGINT NOT NULL REFERENCES payer.claims(claim_id), line_number INT NOT NULL, procedure_code VARCHAR(20) NOT NULL, service_date DATE NOT NULL, billed_amount DECIMAL(14,2) NOT NULL CHECK(billed_amount>=0), allowed_amount DECIMAL(14,2) NOT NULL CHECK(allowed_amount>=0 AND allowed_amount<=billed_amount), paid_amount DECIMAL(14,2) NOT NULL CHECK(paid_amount>=0 AND paid_amount<=allowed_amount), line_status VARCHAR(20) NOT NULL, modified_at DATETIME2(3) NOT NULL, is_deleted BIT NOT NULL DEFAULT 0, UNIQUE(claim_id,line_number));
CREATE TABLE payer.claim_diagnoses (claim_diagnosis_id BIGINT NOT NULL PRIMARY KEY, claim_id BIGINT NOT NULL REFERENCES payer.claims(claim_id), diagnosis_code VARCHAR(20) NOT NULL, sequence_number SMALLINT NOT NULL CHECK(sequence_number>0), modified_at DATETIME2(3) NOT NULL, is_deleted BIT NOT NULL DEFAULT 0, UNIQUE(claim_id,diagnosis_code,sequence_number));
CREATE TABLE payer.authorizations (authorization_id BIGINT NOT NULL PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES payer.members(member_id), provider_id BIGINT NOT NULL, authorization_number VARCHAR(40) NOT NULL UNIQUE, requested_date DATE NOT NULL, decision_date DATE, status VARCHAR(20) NOT NULL, requested_units INT NOT NULL CHECK(requested_units>0), approved_units INT NOT NULL CHECK(approved_units>=0 AND approved_units<=requested_units), modified_at DATETIME2(3) NOT NULL, is_deleted BIT NOT NULL DEFAULT 0);
CREATE TABLE payer.payments (payment_id BIGINT NOT NULL PRIMARY KEY, claim_id BIGINT NOT NULL REFERENCES payer.claims(claim_id), payment_reference VARCHAR(40) NOT NULL UNIQUE, payment_date DATE NOT NULL, paid_amount DECIMAL(14,2) NOT NULL CHECK(paid_amount>=0), payment_status VARCHAR(20) NOT NULL, modified_at DATETIME2(3) NOT NULL, is_deleted BIT NOT NULL DEFAULT 0);
CREATE TABLE payer.claim_adjustments (adjustment_id BIGINT NOT NULL PRIMARY KEY, claim_id BIGINT NOT NULL REFERENCES payer.claims(claim_id), adjustment_type VARCHAR(20) NOT NULL, adjustment_reason VARCHAR(120) NOT NULL, adjustment_amount DECIMAL(14,2) NOT NULL CHECK(adjustment_amount>=0), adjustment_date DATE NOT NULL, modified_at DATETIME2(3) NOT NULL, is_deleted BIT NOT NULL DEFAULT 0);
CREATE INDEX ix_members_modified ON payer.members(modified_at,member_id); CREATE INDEX ix_plans_modified ON payer.plans(modified_at,plan_id); CREATE INDEX ix_enrollment_modified ON payer.member_enrollment(modified_at,enrollment_id); CREATE INDEX ix_claims_modified ON payer.claims(modified_at,claim_id); CREATE INDEX ix_claim_lines_modified ON payer.claim_lines(modified_at,claim_line_id); CREATE INDEX ix_claim_diag_modified ON payer.claim_diagnoses(modified_at,claim_diagnosis_id); CREATE INDEX ix_auth_modified ON payer.authorizations(modified_at,authorization_id); CREATE INDEX ix_payments_modified ON payer.payments(modified_at,payment_id); CREATE INDEX ix_adjustments_modified ON payer.claim_adjustments(modified_at,adjustment_id);
