-- Metadata and audit control schema for ADF orchestration.
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name='control') EXEC('CREATE SCHEMA control');
CREATE TABLE control.source_system (source_system_id INT IDENTITY PRIMARY KEY, source_name VARCHAR(50) NOT NULL UNIQUE, engine VARCHAR(30) NOT NULL, enabled BIT NOT NULL DEFAULT 1, created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE control.ingestion_config (ingestion_config_id INT IDENTITY PRIMARY KEY, source_system_id INT NOT NULL REFERENCES control.source_system(source_system_id), source_schema VARCHAR(128) NOT NULL, source_table VARCHAR(128) NOT NULL, load_type VARCHAR(20) NOT NULL CHECK(load_type IN ('FULL','INCREMENTAL')), primary_key_column VARCHAR(128) NOT NULL, watermark_column VARCHAR(128) NULL, extraction_sql_template NVARCHAR(2000) NOT NULL, destination_path VARCHAR(500) NOT NULL, expected_schema_version VARCHAR(20) NOT NULL, enabled BIT NOT NULL DEFAULT 1, concurrency_group VARCHAR(50) NOT NULL DEFAULT 'default', retry_count TINYINT NOT NULL DEFAULT 3, dq_threshold DECIMAL(5,2) NOT NULL DEFAULT 0, UNIQUE(source_system_id,source_schema,source_table));
CREATE TABLE control.pipeline_run (pipeline_run_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, batch_id VARCHAR(100) NOT NULL UNIQUE, pipeline_name VARCHAR(200) NOT NULL, status VARCHAR(20) NOT NULL, started_at DATETIME2(3) NOT NULL, ended_at DATETIME2(3) NULL, error_message NVARCHAR(2000) NULL);
CREATE TABLE control.table_run (table_run_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, pipeline_run_id UNIQUEIDENTIFIER NOT NULL REFERENCES control.pipeline_run(pipeline_run_id), ingestion_config_id INT NOT NULL REFERENCES control.ingestion_config(ingestion_config_id), status VARCHAR(20) NOT NULL, low_watermark_ts DATETIME2(3) NULL, low_watermark_key VARCHAR(200) NULL, high_watermark_ts DATETIME2(3) NULL, high_watermark_key VARCHAR(200) NULL, row_count BIGINT NULL, file_count INT NULL, started_at DATETIME2(3) NOT NULL, ended_at DATETIME2(3) NULL, error_message NVARCHAR(2000) NULL);
CREATE TABLE control.watermark_state (ingestion_config_id INT NOT NULL PRIMARY KEY REFERENCES control.ingestion_config(ingestion_config_id), last_committed_ts DATETIME2(3) NULL, last_committed_key VARCHAR(200) NULL, updated_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE control.batch_manifest (manifest_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, batch_id VARCHAR(100) NOT NULL, table_run_id UNIQUEIDENTIFIER NOT NULL REFERENCES control.table_run(table_run_id), source_row_count BIGINT NOT NULL, landed_row_count BIGINT NOT NULL, checksum_sha256 CHAR(64) NOT NULL, schema_hash_sha256 CHAR(64) NOT NULL, bronze_path VARCHAR(500) NOT NULL, published_at DATETIME2(3) NULL, status VARCHAR(20) NOT NULL);
CREATE TABLE control.dq_result (dq_result_id BIGINT IDENTITY PRIMARY KEY, batch_id VARCHAR(100) NOT NULL, domain VARCHAR(50) NOT NULL, table_name VARCHAR(128) NOT NULL, rule_name VARCHAR(200) NOT NULL, severity VARCHAR(20) NOT NULL, passed BIT NOT NULL, failed_count BIGINT NOT NULL DEFAULT 0, evaluated_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(), details NVARCHAR(2000) NULL);
CREATE TABLE control.job_dependency (job_dependency_id BIGINT IDENTITY PRIMARY KEY, batch_id VARCHAR(100) NOT NULL, upstream_job VARCHAR(200) NOT NULL, downstream_job VARCHAR(200) NOT NULL, status VARCHAR(20) NOT NULL, UNIQUE(batch_id,upstream_job,downstream_job));
CREATE TABLE control.reprocess_request (request_id VARCHAR(100) PRIMARY KEY, domain VARCHAR(50) NOT NULL, start_business_date DATE NOT NULL, end_business_date DATE NOT NULL, business_key_range VARCHAR(500) NULL, reason NVARCHAR(1000) NOT NULL, requested_by VARCHAR(200) NOT NULL, code_version VARCHAR(100) NOT NULL, contract_version VARCHAR(20) NOT NULL, mode VARCHAR(20) NOT NULL CHECK(mode IN ('DRY_RUN','EXECUTE')), status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED', created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE control.reconciliation_result (reconciliation_id BIGINT IDENTITY PRIMARY KEY, batch_id VARCHAR(100) NOT NULL, domain VARCHAR(50) NOT NULL, source_count BIGINT NOT NULL, silver_count BIGINT NOT NULL, gold_count BIGINT NOT NULL, source_amount DECIMAL(18,2) NULL, gold_amount DECIMAL(18,2) NULL, passed BIT NOT NULL, evaluated_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE control.pipeline_health (health_id BIGINT IDENTITY PRIMARY KEY, check_name VARCHAR(200) NOT NULL, status VARCHAR(20) NOT NULL, observed_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(), details NVARCHAR(2000) NULL);
