-- =============================================================================
-- Phase 7: Snowflake database, schemas, warehouses, roles, and grants.
-- Every statement is rerunnable and uses least-privilege trial-safe defaults.
-- =============================================================================

CREATE DATABASE IF NOT EXISTS HEALTHCARE_DEMO
  COMMENT = 'Synthetic healthcare curated serving layer';

CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DEMO.RAW_STAGE
  COMMENT = 'External stage, manifest table, and transient Gold staging tables';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DEMO.CURATED
  COMMENT = 'Published dimensions, facts, and bridges';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DEMO.KPI
  COMMENT = 'Rebuilt controlled aggregates';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DEMO.AUDIT
  COMMENT = 'Load audit, reconciliation, and error evidence';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DEMO.SECURE_SHARE
  COMMENT = 'Governed BI-facing secure views';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DEMO.SECURITY
  COMMENT = 'Masking and row-access policies';

CREATE WAREHOUSE IF NOT EXISTS WH_HCPIPE_LOADING
  WITH WAREHOUSE_SIZE = 'XSMALL'
       AUTO_SUSPEND = 60
       AUTO_RESUME = TRUE
       INITIALLY_SUSPENDED = TRUE
       STATEMENT_TIMEOUT_IN_SECONDS = 3600
       COMMENT = 'Batch COPY/MERGE loading warehouse';

CREATE WAREHOUSE IF NOT EXISTS WH_HCPIPE_BI
  WITH WAREHOUSE_SIZE = 'XSMALL'
       AUTO_SUSPEND = 60
       AUTO_RESUME = TRUE
       INITIALLY_SUSPENDED = TRUE
       STATEMENT_TIMEOUT_IN_SECONDS = 900
       COMMENT = 'Secure BI query warehouse';

CREATE RESOURCE MONITOR IF NOT EXISTS RM_HCPIPE_LOADING
  WITH CREDIT_QUOTA = 10
       TRIGGERS ON 75 PERCENT DO NOTIFY
                ON 90 PERCENT DO SUSPEND
                ON 100 PERCENT DO SUSPEND_IMMEDIATE
  COMMENT = 'Trial guardrail for loading warehouse';
ALTER WAREHOUSE WH_HCPIPE_LOADING SET RESOURCE_MONITOR = RM_HCPIPE_LOADING;

CREATE ROLE IF NOT EXISTS ROLE_HCPIPE_LOADER
  COMMENT = 'Can execute controlled Snowflake loading procedures';
CREATE ROLE IF NOT EXISTS ROLE_HCPIPE_BI
  COMMENT = 'Read-only access to governed secure views and KPIs';
CREATE ROLE IF NOT EXISTS ROLE_HCPIPE_SECURITY_ADMIN
  COMMENT = 'Manages Snowflake policy objects and grants';

-- Loader needs object creation/maintenance in controlled schemas.
GRANT USAGE ON DATABASE HEALTHCARE_DEMO TO ROLE ROLE_HCPIPE_LOADER;
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT, CREATE PROCEDURE, CREATE SEQUENCE
  ON SCHEMA HEALTHCARE_DEMO.RAW_STAGE TO ROLE ROLE_HCPIPE_LOADER;
GRANT USAGE, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE
  ON SCHEMA HEALTHCARE_DEMO.CURATED TO ROLE ROLE_HCPIPE_LOADER;
GRANT USAGE, CREATE TABLE, CREATE PROCEDURE ON SCHEMA HEALTHCARE_DEMO.KPI TO ROLE ROLE_HCPIPE_LOADER;
GRANT USAGE, CREATE TABLE, CREATE PROCEDURE ON SCHEMA HEALTHCARE_DEMO.AUDIT TO ROLE ROLE_HCPIPE_LOADER;
GRANT USAGE, CREATE VIEW ON SCHEMA HEALTHCARE_DEMO.SECURE_SHARE TO ROLE ROLE_HCPIPE_LOADER;
GRANT USAGE, CREATE MASKING POLICY, CREATE ROW ACCESS POLICY
  ON SCHEMA HEALTHCARE_DEMO.SECURITY TO ROLE ROLE_HCPIPE_SECURITY_ADMIN;

-- Operating grants; table/stage/procedure grants are applied in 004 after objects exist.
GRANT USAGE ON WAREHOUSE WH_HCPIPE_LOADING TO ROLE ROLE_HCPIPE_LOADER;
GRANT OPERATE ON WAREHOUSE WH_HCPIPE_LOADING TO ROLE ROLE_HCPIPE_LOADER;
GRANT USAGE ON DATABASE HEALTHCARE_DEMO TO ROLE ROLE_HCPIPE_BI;
GRANT USAGE ON SCHEMA HEALTHCARE_DEMO.SECURE_SHARE TO ROLE ROLE_HCPIPE_BI;
GRANT USAGE ON SCHEMA HEALTHCARE_DEMO.KPI TO ROLE ROLE_HCPIPE_BI;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTHCARE_DEMO.KPI TO ROLE ROLE_HCPIPE_BI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTHCARE_DEMO.KPI TO ROLE ROLE_HCPIPE_BI;
GRANT USAGE ON WAREHOUSE WH_HCPIPE_BI TO ROLE ROLE_HCPIPE_BI;

GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE ROLE_HCPIPE_SECURITY_ADMIN;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE ROLE_HCPIPE_SECURITY_ADMIN;
GRANT USAGE ON SCHEMA HEALTHCARE_DEMO.SECURITY TO ROLE ROLE_HCPIPE_LOADER;
