-- =============================================================================
-- Azure ADLS Gold Parquet external stage and manifest control table.
-- Storage integration uses Azure application consent; no keys or SAS tokens.
-- Replace only the placeholder tenant/app/storage identifiers before deploy.
-- =============================================================================

CREATE FILE FORMAT IF NOT EXISTS RAW_STAGE.FF_GOLD_PARQUET
  TYPE = PARQUET
  COMPRESSION = SNAPPY
  NULL_IF = ()
  TRIM_SPACE = FALSE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
  USE_LOGICAL_TYPE = TRUE
  BINARY_AS_TEXT = FALSE
  COMMENT = 'Databricks Gold Parquet export format';

CREATE STORAGE INTEGRATION IF NOT EXISTS SI_HCPIPE_ADLS_GOLD
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = AZURE
  ENABLED = TRUE
  AZURE_TENANT_ID = '<AZURE_TENANT_ID>'
  STORAGE_ALLOWED_LOCATIONS = (
    'azure://hcpipe-<ENV>-adlsrgp.dfs.core.windows.net/gold/'
  )
  COMMENT = 'Least-privilege Azure storage integration for the Gold prefix only';

CREATE STAGE IF NOT EXISTS RAW_STAGE.STG_GOLD_EXPORT
  URL = 'azure://hcpipe-<ENV>-adlsrgp.dfs.core.windows.net/gold/export/'
  STORAGE_INTEGRATION = SI_HCPIPE_ADLS_GOLD
  FILE_FORMAT = RAW_STAGE.FF_GOLD_PARQUET
  COMMENT = 'External stage restricted to Gold export files';

CREATE TABLE IF NOT EXISTS AUDIT.LOAD_AUDIT (
  LOAD_AUDIT_SK NUMBER(38,0) IDENTITY,
  BATCH_ID VARCHAR NOT NULL,
  MANIFEST_PATH VARCHAR NOT NULL,
  REPLAY_VERSION VARCHAR,
  STATUS VARCHAR NOT NULL,
  STARTED_AT TIMESTAMP_NTZ NOT NULL,
  COMPLETED_AT TIMESTAMP_NTZ,
  FILES_EXPECTED NUMBER(18,0),
  FILES_LOADED NUMBER(18,0),
  ROWS_EXPECTED NUMBER(38,0),
  ROWS_LOADED NUMBER(38,0),
  ROWS_MERGED NUMBER(38,0),
  ERROR_MESSAGE VARCHAR,
  METRIC_VERSION VARCHAR DEFAULT 'v1',
  CODE_VERSION VARCHAR,
  PROCESSED_AT TIMESTAMP_NTZ,
  CONSTRAINT PK_LOAD_AUDIT PRIMARY KEY (BATCH_ID)
);

CREATE TABLE IF NOT EXISTS AUDIT.LOAD_ERROR (
  LOAD_ERROR_SK NUMBER(38,0) IDENTITY,
  BATCH_ID VARCHAR NOT NULL,
  TABLE_NAME VARCHAR,
  FILE_NAME VARCHAR,
  ROW_NUMBER NUMBER(38,0),
  ERROR_CODE VARCHAR,
  ERROR_MESSAGE VARCHAR,
  RAW_RECORD VARIANT,
  DETECTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS AUDIT.RECONCILIATION (
  RECONCILIATION_SK NUMBER(38,0) IDENTITY,
  BATCH_ID VARCHAR NOT NULL,
  TABLE_NAME VARCHAR NOT NULL,
  CONTROL_NAME VARCHAR NOT NULL,
  EXPECTED_ROWS NUMBER(38,0),
  ACTUAL_ROWS NUMBER(38,0),
  EXPECTED_AMOUNT NUMBER(38,10),
  ACTUAL_AMOUNT NUMBER(38,10),
  STATUS VARCHAR NOT NULL,
  DETECTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_STAGE.MANIFEST (
  BATCH_ID VARCHAR NOT NULL,
  MANIFEST_PATH VARCHAR NOT NULL,
  MANIFEST VARIANT NOT NULL,
  RECEIVED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_MANIFEST PRIMARY KEY (BATCH_ID, MANIFEST_PATH)
);

CREATE TABLE IF NOT EXISTS AUDIT.PUBLISHED_BATCH (
  BATCH_ID VARCHAR NOT NULL,
  MANIFEST_HASH VARCHAR NOT NULL,
  PUBLISHED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  REPLAY_VERSION VARCHAR,
  CONSTRAINT PK_PUBLISHED_BATCH PRIMARY KEY (BATCH_ID)
);

-- Operating grants for objects that now exist.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE RAW_STAGE.MANIFEST TO ROLE ROLE_HCPIPE_LOADER;
GRANT SELECT, INSERT, UPDATE ON TABLE AUDIT.LOAD_AUDIT TO ROLE ROLE_HCPIPE_LOADER;
GRANT SELECT, INSERT ON TABLE AUDIT.LOAD_ERROR TO ROLE ROLE_HCPIPE_LOADER;
GRANT SELECT, INSERT, UPDATE ON TABLE AUDIT.RECONCILIATION TO ROLE ROLE_HCPIPE_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE AUDIT.PUBLISHED_BATCH TO ROLE ROLE_HCPIPE_LOADER;
GRANT USAGE ON FILE FORMAT RAW_STAGE.FF_GOLD_PARQUET TO ROLE ROLE_HCPIPE_LOADER;
GRANT USAGE ON STAGE RAW_STAGE.STG_GOLD_EXPORT TO ROLE ROLE_HCPIPE_LOADER;
