-- =============================================================================
-- Controlled load metadata. This table drives replay protection, generic
-- validation, and transactional MERGE behavior.
-- =============================================================================

CREATE TABLE IF NOT EXISTS RAW_STAGE.LOAD_TABLE_CONTROL (
  TABLE_NAME VARCHAR NOT NULL,
  SCHEMA_NAME VARCHAR NOT NULL DEFAULT 'CURATED',
  MERGE_TYPE VARCHAR NOT NULL,
  MERGE_KEY VARCHAR NOT NULL,
  LOAD_ORDER NUMBER(38,0) NOT NULL,
  EXPECTED_COLUMNS NUMBER(38,0),
  CONSTRAINT PK_LOAD_TABLE_CONTROL PRIMARY KEY (TABLE_NAME)
);

INSERT INTO RAW_STAGE.LOAD_TABLE_CONTROL
  (TABLE_NAME, MERGE_TYPE, MERGE_KEY, LOAD_ORDER, EXPECTED_COLUMNS)
SELECT 'DIM_DATE', 'SCD1', 'DATE_KEY', 10, 13
UNION ALL SELECT 'DIM_DIAGNOSIS', 'SCD1', 'DIAGNOSIS_CODE', 20, 14
UNION ALL SELECT 'DIM_PROCEDURE', 'SCD1', 'PROCEDURE_CODE', 30, 14
UNION ALL SELECT 'DIM_MEDICATION', 'SCD1', 'MEDICATION_ID', 40, 16
UNION ALL SELECT 'DIM_FACILITY', 'SCD1', 'FACILITY_ID', 50, 17
UNION ALL SELECT 'DIM_PLAN', 'SCD1', 'PLAN_ID', 60, 17
UNION ALL SELECT 'DIM_PATIENT', 'SCD2', 'PATIENT_ID', 70, 25
UNION ALL SELECT 'DIM_MEMBER', 'SCD2', 'MEMBER_ID', 80, 21
UNION ALL SELECT 'DIM_PROVIDER', 'SCD2', 'PROVIDER_ID', 90, 19
UNION ALL SELECT 'FACT_ENCOUNTER', 'FACT', 'SURROGATE_KEY', 100, 17
UNION ALL SELECT 'FACT_CLAIM', 'FACT', 'SURROGATE_KEY', 110, 17
UNION ALL SELECT 'FACT_CLAIM_LINE', 'FACT', 'SURROGATE_KEY', 120, 17
UNION ALL SELECT 'FACT_PAYMENT', 'FACT', 'SURROGATE_KEY', 130, 17
UNION ALL SELECT 'FACT_OBSERVATION', 'FACT', 'SURROGATE_KEY', 140, 17
UNION ALL SELECT 'FACT_PRESCRIPTION', 'FACT', 'SURROGATE_KEY', 150, 17
UNION ALL SELECT 'FACT_AUTHORIZATION', 'FACT', 'SURROGATE_KEY', 160, 17
UNION ALL SELECT 'BRIDGE_CLAIM_DIAGNOSIS', 'BRIDGE', 'BRIDGE_KEY', 170, 12
UNION ALL SELECT 'BRIDGE_PROVIDER_FACILITY', 'BRIDGE', 'BRIDGE_KEY', 180, 13
UNION ALL SELECT 'BRIDGE_MEMBER_ENROLLMENT', 'BRIDGE', 'BRIDGE_KEY', 190, 15
WHERE NOT EXISTS (SELECT 1 FROM RAW_STAGE.LOAD_TABLE_CONTROL);

CREATE TABLE IF NOT EXISTS AUDIT.AUTHORIZED_BATCH (
  BATCH_ID VARCHAR NOT NULL,
  ROLE_NAME VARCHAR NOT NULL,
  AUTHORIZED_BY VARCHAR NOT NULL,
  AUTHORIZED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_AUTHORIZED_BATCH PRIMARY KEY (BATCH_ID, ROLE_NAME)
);

GRANT SELECT, INSERT, DELETE ON TABLE RAW_STAGE.LOAD_TABLE_CONTROL TO ROLE ROLE_HCPIPE_LOADER;
GRANT SELECT, INSERT, DELETE ON TABLE AUDIT.AUTHORIZED_BATCH TO ROLE ROLE_HCPIPE_LOADER;

CREATE TABLE IF NOT EXISTS RAW_STAGE.MANIFEST_FILE (
  BATCH_ID VARCHAR NOT NULL,
  TABLE_NAME VARCHAR NOT NULL,
  FILE_PATH VARCHAR NOT NULL,
  FILE_SHA256 VARCHAR,
  FILE_SIZE_BYTES NUMBER(38,0),
  ROW_COUNT NUMBER(38,0),
  CONSTRAINT PK_MANIFEST_FILE PRIMARY KEY (BATCH_ID, TABLE_NAME, FILE_PATH)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE RAW_STAGE.MANIFEST_FILE TO ROLE ROLE_HCPIPE_LOADER;
