-- Governed dynamic masking. Role ROLE_HCPIPE_LOADER and ROLE_HCPIPE_SECURITY_ADMIN
-- see values for pipeline operations; all other roles receive NULL.

CREATE MASKING POLICY IF NOT EXISTS SECURITY.MASK_STRING_PHI AS
  (VAL VARCHAR) RETURNS VARCHAR ->
  CASE WHEN CURRENT_ROLE() IN ('ROLE_HCPIPE_LOADER', 'ROLE_HCPIPE_SECURITY_ADMIN') THEN VAL ELSE NULL END;

CREATE MASKING POLICY IF NOT EXISTS SECURITY.MASK_DATE_PHI AS
  (VAL DATE) RETURNS DATE ->
  CASE WHEN CURRENT_ROLE() IN ('ROLE_HCPIPE_LOADER', 'ROLE_HCPIPE_SECURITY_ADMIN') THEN VAL ELSE NULL END;

-- Batch-based row access: loaders/administrators see all rows; BI sees rows only
-- for batches explicitly authorized for the current role in AUDIT.AUTHORIZED_BATCH.
CREATE ROW ACCESS POLICY IF NOT EXISTS SECURITY.RAP_CURRENT_BATCH AS
  (BATCH_ID VARCHAR) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('ROLE_HCPIPE_LOADER', 'ROLE_HCPIPE_SECURITY_ADMIN')
  OR EXISTS (
       SELECT 1 FROM AUDIT.AUTHORIZED_BATCH A
       WHERE A.BATCH_ID = BATCH_ID AND A.ROLE_NAME = CURRENT_ROLE()
  );

-- Apply masking policies
ALTER TABLE CURATED.DIM_PATIENT ALTER COLUMN ENTERPRISE_PERSON_ID SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_PATIENT ALTER COLUMN FIRST_NAME SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_PATIENT ALTER COLUMN LAST_NAME SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_PATIENT ALTER COLUMN DATE_OF_BIRTH SET MASKING POLICY SECURITY.MASK_DATE_PHI;
ALTER TABLE CURATED.DIM_PATIENT ALTER COLUMN EMAIL SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_PATIENT ALTER COLUMN PHONE SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_PATIENT ALTER COLUMN ADDRESS_LINE1 SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_PATIENT ALTER COLUMN SYNTHETIC_NATIONAL_ID SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_MEMBER ALTER COLUMN ENTERPRISE_PERSON_ID SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_MEMBER ALTER COLUMN FIRST_NAME SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_MEMBER ALTER COLUMN LAST_NAME SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_MEMBER ALTER COLUMN DATE_OF_BIRTH SET MASKING POLICY SECURITY.MASK_DATE_PHI;
ALTER TABLE CURATED.DIM_MEMBER ALTER COLUMN MEMBER_NUMBER SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_MEMBER ALTER COLUMN EMAIL SET MASKING POLICY SECURITY.MASK_STRING_PHI;
ALTER TABLE CURATED.DIM_MEMBER ALTER COLUMN PHONE SET MASKING POLICY SECURITY.MASK_STRING_PHI;

-- Apply row-access policies
ALTER TABLE CURATED.DIM_PATIENT ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.DIM_MEMBER ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.DIM_PROVIDER ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.DIM_FACILITY ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.DIM_PLAN ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.DIM_DATE ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.DIM_DIAGNOSIS ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.DIM_PROCEDURE ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.DIM_MEDICATION ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.FACT_ENCOUNTER ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.FACT_CLAIM ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.FACT_CLAIM_LINE ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.FACT_PAYMENT ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.FACT_AUTHORIZATION ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.FACT_OBSERVATION ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.FACT_PRESCRIPTION ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.BRIDGE_CLAIM_DIAGNOSIS ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.BRIDGE_PROVIDER_FACILITY ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
ALTER TABLE CURATED.BRIDGE_MEMBER_ENROLLMENT ADD ROW ACCESS POLICY SECURITY.RAP_CURRENT_BATCH ON (_GOLD_BATCH_ID);
