-- =============================================================================
-- Controlled KPI serving tables. Aggregates are rebuilt by batch and version.
-- =============================================================================
CREATE TABLE IF NOT EXISTS KPI.KPI_BATCH_TABLE_COUNTS (
  BATCH_ID VARCHAR NOT NULL,
  TABLE_NAME VARCHAR NOT NULL,
  ROW_COUNT NUMBER(38,0) NOT NULL,
  DISTINCT_KEYS NUMBER(38,0),
  MIN_EFFECTIVE_FROM TIMESTAMP_NTZ,
  MAX_EFFECTIVE_TO TIMESTAMP_NTZ,
  METRIC_VERSION VARCHAR DEFAULT 'v1',
  AS_OF_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_KPI_BATCH_TABLE_COUNTS PRIMARY KEY (BATCH_ID, TABLE_NAME, METRIC_VERSION)
);

CREATE TABLE IF NOT EXISTS KPI.KPI_FINANCIAL_RECONCILIATION (
  BATCH_ID VARCHAR NOT NULL,
  SOURCE_ROWS NUMBER(38,0),
  SILVER_ROWS NUMBER(38,0),
  GOLD_ROWS NUMBER(38,0),
  SNOWFLAKE_ROWS NUMBER(38,0),
  SOURCE_AMOUNT NUMBER(38,10),
  SILVER_AMOUNT NUMBER(38,10),
  GOLD_AMOUNT NUMBER(38,10),
  SNOWFLAKE_AMOUNT NUMBER(38,10),
  ROW_DIFFERENCE NUMBER(38,0),
  AMOUNT_DIFFERENCE NUMBER(38,10),
  STATUS VARCHAR,
  METRIC_VERSION VARCHAR DEFAULT 'v1',
  AS_OF_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_KPI_FINANCIAL_RECON PRIMARY KEY (BATCH_ID, METRIC_VERSION)
);

GRANT SELECT ON TABLE KPI.KPI_BATCH_TABLE_COUNTS TO ROLE ROLE_HCPIPE_BI;
GRANT SELECT ON TABLE KPI.KPI_FINANCIAL_RECONCILIATION TO ROLE ROLE_HCPIPE_BI;
