-- =============================================================================
-- Generic transactional MERGE helpers. Curated Gold rows are addressed by the
-- stable surrogate key generated by the Gold contract; MERGE is therefore both
-- idempotent and safe to replay.
-- =============================================================================
CREATE OR REPLACE PROCEDURE RAW_STAGE.USP_MERGE_CURATED(
  P_BATCH_ID VARCHAR,
  P_TABLE_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  v_sql VARCHAR;
  v_columns VARCHAR;
  v_update VARCHAR;
  v_merge_key VARCHAR;
  v_merged NUMBER;
  v_curated VARCHAR;
  v_staging VARCHAR;
BEGIN
  SELECT 'CURATED.' || UPPER(TABLE_NAME), 'RAW_STAGE.STG_' || UPPER(TABLE_NAME), UPPER(MERGE_KEY)
    INTO :v_curated, :v_staging, :v_merge_key
    FROM RAW_STAGE.LOAD_TABLE_CONTROL
   WHERE UPPER(TABLE_NAME) = UPPER(:P_TABLE_NAME);

  IF v_merge_key IS NULL THEN
    RETURN 'ERROR: table not controlled';
  END IF;

  SELECT 'CURATED.' || UPPER(TABLE_NAME), 'RAW_STAGE.STG_' || UPPER(TABLE_NAME), LISTAGG(UPPER(COLUMN_NAME), ', ')
    INTO :v_curated, :v_staging, :v_columns
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE UPPER(TABLE_SCHEMA) = 'CURATED'
     AND UPPER(TABLE_NAME) = UPPER(:P_TABLE_NAME)
     AND UPPER(COLUMN_NAME) NOT IN ('_COPY_FILE_NAME', '_COPY_ROW_NUMBER')
   GROUP BY 1, 2;

  IF v_columns IS NULL THEN
    RETURN 'ERROR: curated table not found';
  END IF;

  SELECT LISTAGG('c.' || UPPER(COLUMN_NAME) || ' = s.' || UPPER(COLUMN_NAME), ', ')
    INTO :v_update
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE UPPER(TABLE_SCHEMA) = 'CURATED'
     AND UPPER(TABLE_NAME) = UPPER(:P_TABLE_NAME)
     AND UPPER(COLUMN_NAME) <> v_merge_key;

  v_sql := 'MERGE INTO ' || v_curated || ' c USING (SELECT * FROM ' || v_staging ||
           ' WHERE _GOLD_BATCH_ID = ?) s ON c.' || v_merge_key || ' = s.' || v_merge_key ||
           ' WHEN MATCHED THEN UPDATE SET ' ||
           v_update || ' WHEN NOT MATCHED THEN INSERT (' || v_columns || ') VALUES (' ||
           REGEXP_REPLACE(v_columns, '([A-Z0-9_]+)', 's.\\1') || ')';

  EXECUTE IMMEDIATE :v_sql USING (:P_BATCH_ID);
  v_merged := SQLROWCOUNT;
  RETURN 'MERGED:' || UPPER(:P_TABLE_NAME) || ':' || v_merged;
EXCEPTION
  WHEN OTHER THEN
    RETURN 'ERROR: ' || SQLERRM;
END;
$$;

CREATE OR REPLACE PROCEDURE RAW_STAGE.USP_MERGE_SCD2_DIMENSION(
  P_BATCH_ID VARCHAR,
  P_TABLE_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  v_result VARCHAR;
BEGIN
  -- Gold already materializes versioned SCD2 rows with stable surrogate keys.
  -- Preserve exact effective_from/effective_to/is_current values while making
  -- the operation replay-safe.
  v_result := RAW_STAGE.USP_MERGE_CURATED(:P_BATCH_ID, :P_TABLE_NAME);
  RETURN v_result;
END;
$$;

CREATE OR REPLACE PROCEDURE RAW_STAGE.USP_MERGE_SCD1_DIMENSION(
  P_BATCH_ID VARCHAR,
  P_TABLE_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  v_result VARCHAR;
BEGIN
  v_result := RAW_STAGE.USP_MERGE_CURATED(:P_BATCH_ID, :P_TABLE_NAME);
  RETURN v_result;
END;
$$;

CREATE OR REPLACE PROCEDURE RAW_STAGE.USP_MERGE_FACT(
  P_BATCH_ID VARCHAR,
  P_TABLE_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  v_result VARCHAR;
BEGIN
  v_result := RAW_STAGE.USP_MERGE_CURATED(:P_BATCH_ID, :P_TABLE_NAME);
  RETURN v_result;
END;
$$;
