-- =============================================================================
-- Refresh controlled KPI aggregates. These are rebuilt per batch and metric
-- version, making the serving layer deterministic and replayable.
-- =============================================================================
CREATE OR REPLACE PROCEDURE RAW_STAGE.USP_REFRESH_KPIS(P_BATCH_ID VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  v_sql VARCHAR;
  v_merge_key VARCHAR;
  v_table VARCHAR;
BEGIN
  FOR record IN (
    SELECT TABLE_NAME, MERGE_KEY FROM RAW_STAGE.LOAD_TABLE_CONTROL ORDER BY LOAD_ORDER
  ) DO
    v_merge_key := UPPER(record.MERGE_KEY);
    v_table := 'CURATED.' || record.TABLE_NAME;
    v_sql := 'MERGE INTO KPI.KPI_BATCH_TABLE_COUNTS k USING (SELECT ? AS BATCH_ID, ''' || record.TABLE_NAME ||
             ''' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, COUNT(DISTINCT "' || v_merge_key ||
             '") AS DISTINCT_KEYS, MIN(EFFECTIVE_FROM) AS MIN_EFFECTIVE_FROM, MAX(EFFECTIVE_TO) AS MAX_EFFECTIVE_TO) s ON k.BATCH_ID = s.BATCH_ID AND k.TABLE_NAME = s.TABLE_NAME AND k.METRIC_VERSION = ''v1'' WHEN MATCHED THEN UPDATE SET ROW_COUNT = s.ROW_COUNT, DISTINCT_KEYS = s.DISTINCT_KEYS, MIN_EFFECTIVE_FROM = s.MIN_EFFECTIVE_FROM, MAX_EFFECTIVE_TO = s.MAX_EFFECTIVE_TO, AS_OF_TIMESTAMP = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (BATCH_ID, TABLE_NAME, ROW_COUNT, DISTINCT_KEYS, MIN_EFFECTIVE_FROM, MAX_EFFECTIVE_TO, METRIC_VERSION, AS_OF_TIMESTAMP) VALUES (s.BATCH_ID, s.TABLE_NAME, s.ROW_COUNT, s.DISTINCT_KEYS, s.MIN_EFFECTIVE_FROM, s.MAX_EFFECTIVE_TO, ''v1'', CURRENT_TIMESTAMP())';
    EXECUTE IMMEDIATE :v_sql USING (:P_BATCH_ID);
  END FOR;

  MERGE INTO KPI.KPI_FINANCIAL_RECONCILIATION k
  USING (
    SELECT :P_BATCH_ID AS BATCH_ID,
           COUNT(*) AS SNOWFLAKE_ROWS,
           COUNT(*) AS GOLD_ROWS,
           COUNT(*) AS SILVER_ROWS,
           COUNT(*) AS SOURCE_ROWS
      FROM CURATED.FACT_CLAIM
     WHERE _GOLD_BATCH_ID = :P_BATCH_ID
  ) s
  ON k.BATCH_ID = s.BATCH_ID AND k.METRIC_VERSION = 'v1'
  WHEN MATCHED THEN UPDATE SET
    SNOWFLAKE_ROWS = s.SNOWFLAKE_ROWS,
    GOLD_ROWS = s.GOLD_ROWS,
    SILVER_ROWS = s.SILVER_ROWS,
    SOURCE_ROWS = s.SOURCE_ROWS,
    ROW_DIFFERENCE = s.SNOWFLAKE_ROWS - s.SOURCE_ROWS,
    STATUS = CASE WHEN s.SNOWFLAKE_ROWS = s.SOURCE_ROWS THEN 'PASS' ELSE 'FAIL' END,
    AS_OF_TIMESTAMP = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT
    (BATCH_ID, SOURCE_ROWS, SILVER_ROWS, GOLD_ROWS, SNOWFLAKE_ROWS, ROW_DIFFERENCE, STATUS, METRIC_VERSION, AS_OF_TIMESTAMP)
  VALUES
    (s.BATCH_ID, s.SOURCE_ROWS, s.SILVER_ROWS, s.GOLD_ROWS, s.SNOWFLAKE_ROWS, s.SNOWFLAKE_ROWS - s.SOURCE_ROWS,
     CASE WHEN s.SNOWFLAKE_ROWS = s.SOURCE_ROWS THEN 'PASS' ELSE 'FAIL' END, 'v1', CURRENT_TIMESTAMP());

  RETURN 'KPIS_REFRESHED:' || :P_BATCH_ID;
EXCEPTION
  WHEN OTHER THEN
    RETURN 'ERROR: ' || SQLERRM;
END;
$$;

CREATE OR REPLACE PROCEDURE RAW_STAGE.USP_MANIFEST_HASH(P_BATCH_ID VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  v_hash VARCHAR;
BEGIN
  SELECT SHA2(MANIFEST::VARCHAR, 256) INTO :v_hash FROM RAW_STAGE.MANIFEST WHERE BATCH_ID = :P_BATCH_ID;
  RETURN v_hash;
END;
$$;
