-- Secure views are the only BI-facing presentation objects. They preserve the
-- curated grain and inherit masking/row-access policy enforcement.

CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_DIM_PATIENT AS SELECT * FROM CURATED.DIM_PATIENT;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_DIM_MEMBER AS SELECT * FROM CURATED.DIM_MEMBER;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_DIM_PROVIDER AS SELECT * FROM CURATED.DIM_PROVIDER;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_DIM_FACILITY AS SELECT * FROM CURATED.DIM_FACILITY;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_DIM_PLAN AS SELECT * FROM CURATED.DIM_PLAN;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_DIM_DATE AS SELECT * FROM CURATED.DIM_DATE;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_DIM_DIAGNOSIS AS SELECT * FROM CURATED.DIM_DIAGNOSIS;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_DIM_PROCEDURE AS SELECT * FROM CURATED.DIM_PROCEDURE;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_DIM_MEDICATION AS SELECT * FROM CURATED.DIM_MEDICATION;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_FACT_ENCOUNTER AS SELECT * FROM CURATED.FACT_ENCOUNTER;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_FACT_CLAIM AS SELECT * FROM CURATED.FACT_CLAIM;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_FACT_CLAIM_LINE AS SELECT * FROM CURATED.FACT_CLAIM_LINE;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_FACT_PAYMENT AS SELECT * FROM CURATED.FACT_PAYMENT;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_FACT_AUTHORIZATION AS SELECT * FROM CURATED.FACT_AUTHORIZATION;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_FACT_OBSERVATION AS SELECT * FROM CURATED.FACT_OBSERVATION;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_FACT_PRESCRIPTION AS SELECT * FROM CURATED.FACT_PRESCRIPTION;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_BRIDGE_CLAIM_DIAGNOSIS AS SELECT * FROM CURATED.BRIDGE_CLAIM_DIAGNOSIS;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_BRIDGE_PROVIDER_FACILITY AS SELECT * FROM CURATED.BRIDGE_PROVIDER_FACILITY;
CREATE SECURE VIEW IF NOT EXISTS SECURE_SHARE.V_BRIDGE_MEMBER_ENROLLMENT AS SELECT * FROM CURATED.BRIDGE_MEMBER_ENROLLMENT;

-- Secure-view grants
GRANT SELECT ON ALL VIEWS IN SCHEMA SECURE_SHARE TO ROLE ROLE_HCPIPE_BI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SECURE_SHARE TO ROLE ROLE_HCPIPE_BI;
